# Theme Settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"
# Site Settings
locale: "ar"
rtl: true
title: "دفتر الحكايات"
title_separator: "-"
name: "عدلي رغدة"
description: "مدونة قصص ومقالات تعليمية"
url: ""
baseurl: "/raghda-chaima"
# Navigation
masthead_title: "دفتر الحكايات"
breadcrumbs: true
words_per_minute: 200
enable_copy_code_button: true
# Author Info
author:
  name: "عدلي رغدة"
  avatar: ""
  bio: "كاتبة قصص ومقالات تعليمية تهتم بنشر المعرفة بأسلوب مبسط."
  location: "الجزائر"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/raghda-chaima"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:raghdachaimaa@gmail.com"
# Footer Links
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/raghda-chaima"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:raghdachaimaa@gmail.com"
  since: "2025"
# Comments
comments:
  provider: false
# SEO
google_site_verification: ""
bing_site_verification: ""
# Search
search: true
search_full_content: false
search_provider: lunr
# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
# Pagination
paginate: 5
paginate_path: /page:num/
# Category and Tag Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# Markdown & Syntax Highlighting
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed
# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
# Defaults for Posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
# Include & Exclude
include:
  - .htaccess
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - node_modules
  - README.md
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - Rakefile
  - /docs
  - /test
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /:categories/:title/
timezone: Africa/Algiers
