# Site Settings
locale: "ar"
title: "دفتر الحكايات"
description: "مدونة قصص ومقالات تعليمية"
url: "https://djameldidin.github.io"
baseurl: "/minimal-mistakes"

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Author Info
author:
  name: "عدلي رغدة"
  avatar: ""
  bio: "كاتبة قصص ومقالات تعليمية تهتم بنشر المعرفة بأسلوب مبسط."
  location: "الجزائر"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/djameldidin"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:raghdachaimaa@gmail.com"

# Site Navigation
masthead_links:
  - title: "الرئيسية"
    url: /
  - title: "المقالات"
    url: /year-archive/
  - title: "عن الكاتب"
    url: /about/

# Other settings
plugins:
  - jekyll-remote-theme
