#===========================================================
# SITE SETTINGS
#===========================================================

locale: "ar"
title: "دفتر الحكايات"
description: "مدونة قصص ومقالات تعليمية"
url: "https://djameldidin.github.io"
baseurl: ""  # موقع رئيسي، لا تضع مسار فرعي
repository: "djameldidin/djameldidin.github.io"

#===========================================================
# THEME SETTINGS
#===========================================================

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"
header:
  overlay_color: "#000"
  overlay_filter: "0.3"

#===========================================================
# AUTHOR SETTINGS
#===========================================================

author:
  name: "عدلي رغدة"
  avatar: ""
  bio: "كاتبة قصص و
