#===========================================================
# SITE SETTINGS
#===========================================================

locale: "ar"
title: "دفتر الحكايات"
description: "مدونة قصص ومقالات تعليمية"
url: "https://djameldidin.github.io"
baseurl: ""
repository: "djameldidin/djameldidin.github.io"

#===========================================================
# THEME SETTINGS
#===========================================================

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"
header:
  overlay_color: "#000"
  overlay_filter: "0.3"

#===========================================================
# AUTHOR SETTINGS
#===========================================================

author:
  name: "عدلي رغدة"
  avatar: ""
  bio: "كاتبة قصص ومقالات تعليمية تهتم بنشر المعرفة بأسلوب مبسط."
  location: "الجزائر"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/djameldidin"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:raghdachaimaa@gmail.com"

#===========================================================
# NAVIGATION
#===========================================================

masthead_links:
  - title: "الرئيسية"
    url: /
  - title: "المقالات"
    url: /year-archive/
  - title: "التصنيفات"
    url: /categories/
  - title: "عن الكاتب"
    url: /about/

#===========================================================
# PLUGINS & DEFAULTS
#===========================================================

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

paginate: 5
paginate_path: "/page:num/"
future: true

# Archive Settings
category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
  - scope:
      path: ""
    values:
      layout: null
